version: "3"
services:
  node-app: 
    image: mo201/node-app-docker
    env_file:
      - ./.env
    depends_on:
      - redis
      - mongo

  mongo:
   image: mongo
   restart: always
   volumes:
    - mongo-db:/data/db #Named volume
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example    

  redis:
    image: redis
  
  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
volumes:
  mongo-db: 
  postgres-db: